name: terraform validations

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  tf_version: 'latest'

jobs:
  terraform:
    runs-on: ubuntu-18.04
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
    - name: 'Terraform Fmt'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.tf_version }}
        tf_actions_subcommand: 'fmt'
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.tf_version }}
        tf_actions_subcommand: 'init'
    - name: 'Terraform Validate'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.tf_version }}
        tf_actions_subcommand: 'validate'
